image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker run $IMAGE_TAG shippyd --version
    - docker run $IMAGE_TAG shippy --version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
  only:
    - master
